<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class GagBase extends MagratheaModel implements iMagratheaModel {

	public $id, $origin_id, $text, $tags, $source, $used_in;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "gags";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["origin_id"] = "int";
		$this->dbValues["text"] = "text";
		$this->dbValues["tags"] = "string";
		$this->dbValues["source"] = "text";
		$this->dbValues["used_in"] = "text";

		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

	}

	// >>> relations:

}

class GagControlBase extends MagratheaModelControl {
	protected static $modelName = "Gag";
	protected static $dbTable = "gags";
}
?>